# --------------------------------------------------- #
#             การตั้งค่าปลั๊กอิน BrsuShards              #
# --------------------------------------------------- #

settings:
  # เปิดหรือปิดระบบแจก Shards อัตโนมัติสำหรับผู้เล่นที่ออนไลน์
  play-shards-enabled: true
  # เวลา (หน่วยเป็นนาที) ในการแจก Shards แต่ละครั้ง
  interval-minutes: 10
  # จำนวน Shards ที่จะแจกให้ผู้เล่นแต่ละคนในแต่ละรอบ
  shards-per-interval: 1

# ตั้งค่า Title และ Subtitle ตอนผู้เล่นเข้าเขต AFK Pool
afk-pool-entry:
  enabled: true
  title: "&b&lเข้าสู่เขต AFK"
  subtitle: "&eคุณจะได้รับรางวัลเมื่อยืนอยู่ในบริเวณนี้"
  # ระยะเวลาการแสดงผล (หน่วยเป็น tick, 20 ticks = 1 วินาที)
  fade-in-ticks: 10
  stay-ticks: 40
  fade-out-ticks: 20

# เสียงเอฟเฟกต์สำหรับการกระทำต่างๆ
sounds:
  open-shop: "minecraft:block.note_block.harp"
  click-buy: "minecraft:ui.button.click"
  buy-success: "minecraft:block.note_block.pling"
  buy-cancel: "minecraft:entity.villager.no"
  buy-fail: "minecraft:entity.villager.no"
  shards-receive: "minecraft:entity.experience_orb.pickup"

# ข้อความทั้งหมดของปลั๊กอินที่สามารถตั้งค่าได้
messages:
  only-in-game: "&cคำสั่งนี้ใช้ได้เฉพาะในเกมเท่านั้น"
  no-permission: "&cคุณไม่มีสิทธิ์ใช้งานคำสั่งนี้!"
  not-enough-shards: "&cคุณมี Shards ไม่เพียงพอ!"
  buy-success: "&aซื้อ %item% สำเร็จ!"
  buy-cancelled: "&cยกเลิกการซื้อแล้ว"
  reload-success: "&aรีโหลดการตั้งค่าสำเร็จ!"
  item-added: "&aเพิ่มไอเทมลงร้านค้าสำเร็จ!"
  set-success: "&aตั้งค่า Shards ของ %player% เป็น %amount% สำเร็จ"
  shards-set: "&eยอด Shards ของคุณถูกตั้งค่าเป็น &f%amount% &eโดยแอดมิน"
  you-have-shards: "&eคุณมี: &f%shards% Shards"
  shop-title: "&6ร้านค้า Shard"
  confirm-title: "&eยืนยันการซื้อ"
  shards-receive: "&aคุณได้รับ &e+%amount% &aShards!"
  shards-receive-bar: "&a+%amount% Shards!"
  # ข้อความสำหรับ AFK Pool
  afkpool-wand-given: "&aคุณได้รับ AFK Pool Wand!"
  afkpool-pos1-set: "&aกำหนดจุดที่ 1 แล้วที่: &e%location%"
  afkpool-pos2-set: "&aกำหนดจุดที่ 2 แล้วที่: &e%location%"
  afkpool-created: "&aสร้าง AFK Pool ชื่อ &e%name% &aสำเร็จ!"
  afkpool-deleted: "&cลบ AFK Pool ชื่อ &e%name% &cสำเร็จแล้ว"
  afkpool-list-header: "&6--- รายชื่อ AFK Pools ---"
  afkpool-list-item: "&e- %name% &7(ให้ &f%shards% &7Shards ทุก &f%time% &7วินาที)"
  afkpool-list-empty: "&cยังไม่มี AFK Pool ใดๆถูกสร้างขึ้น"
  afkpool-not-exist: "&cไม่พบ AFK Pool ที่ชื่อ &e%name%"
  afkpool-name-exists: "&cมี AFK Pool ที่ชื่อ &e%name% &cอยู่แล้ว"
  afkpool-no-selection: "&cคุณต้องกำหนดพื้นที่ด้วย Wand ก่อน! (จุดที่ 1 และ 2)"
  afkpool-invalid-number: "&cค่าเวลาและจำนวนต้องเป็นตัวเลขเท่านั้น!"
  afkpool-reward-message: "&aคุณได้รับ &e+%shards% &aShards จากการ AFK!"
  afkpool-countdown-bar: "&aคุณจะได้รับ &e+%shards% Shards &aจากโซน &b%pool% &aในอีก &f%time% &aวินาที"

# การตั้งค่าสำหรับหน้าต่างกราฟิก (GUI)
shop-ui:
  # บรรทัดคำอธิบาย (lore) ที่จะถูกเพิ่มเข้าไปในไอเทมร้านค้าเพื่อแสดงราคา
  # %cost% จะถูกแทนที่ด้วยราคาของไอเทม
  price-lore: "&eราคา: &f%cost% Shards"

  # ไอเทมที่ใช้เป็นช่องว่างสำหรับตกแต่งพื้นหลัง GUI
  blank:
    type: GRAY_STAINED_GLASS_PANE
    # ช่องที่จะเติมด้วยไอเทมนี้
    slots: []
    display: " "

  # ไอเทมที่ใช้สำหรับช่องที่ตกแต่งเท่านั้นและไม่สามารถซื้อได้
  cannotbuy:
    # รายชื่อช่องที่จะเติมด้วยไอเทมนี้ในร้านค้าหลัก
    slots: []
    type: BLACK_STAINED_GLASS_PANE
    display: "&7ไม่มีไว้สำหรับขาย"
    lore:
      - "&8ไอเทมชิ้นนี้ไม่สามารถซื้อได้"

  # ปุ่ม 'ยกเลิก' ในหน้าต่างยืนยันการซื้อ
  cancel:
    type: RED_STAINED_GLASS_PANE
    # ช่องสำหรับปุ่มยกเลิก
    slot: 11
    display: "&cยกเลิก"

  # ปุ่ม 'ยืนยัน' ในหน้าต่างยืนยันการซื้อ
  confirm:
    type: GREEN_STAINED_GLASS_PANE
    # ช่องสำหรับปุ่มยืนยัน
    slot: 15
    display: "&aยืนยัน"

  # ช่องที่ใช้แสดงไอเทมที่กำลังจะซื้อในหน้าต่างยืนยัน
  item-slot: 13