# --------------------------------------------------- #
#             การตั้งค่าปลั๊กอิน BrsuShards              #
# --------------------------------------------------- #

settings:
  # เปิดหรือปิดระบบแจก Shards อัตโนมัติสำหรับผู้เล่นที่ออนไลน์
  # ตั้งค่าเป็น 'true' เพื่อเปิดใช้งาน, 'false' เพื่อปิดใช้งาน
  play-shards-enabled: true
  
  # เวลา (หน่วยเป็นนาที) ในการแจก Shards แต่ละครั้ง
  interval-minutes: 10
  
  # จำนวน Shards ที่จะแจกให้ผู้เล่นแต่ละคนในแต่ละรอบ
  shards-per-interval: 1

# เสียงเอฟเฟกต์สำหรับการกระทำต่างๆ
# คุณสามารถค้นหารายชื่อเสียงได้จาก Minecraft Wiki
sounds:
  # เสียงเมื่อผู้เล่นเปิดร้านค้า
  open-shop: "minecraft:block.note_block.harp"
  
  # เสียงเมื่อผู้เล่นคลิกไอเทมในร้านค้า
  click-buy: "minecraft:ui.button.click"
  
  # เสียงเมื่อซื้อของสำเร็จ
  buy-success: "minecraft:entity.experience_orb.pickup"

  # เสียงเมื่อยกเลิกการซื้อ
  buy-cancel: "minecraft:entity.villager.no"

  # เสียงเมื่อการซื้อล้มเหลว (เช่น แต้มไม่พอ)
  buy-fail: "minecraft:entity.villager.no"

  # เสียงเมื่อได้รับ Shards
  shards-receive: "minecraft:entity.player.levelup"

# ข้อความทั้งหมดของปลั๊กอินที่สามารถตั้งค่าได้
# คุณสามารถใช้โค้ดสีของ Minecraft ด้วยเครื่องหมาย '&'
messages:
  only-in-game: "&cคำสั่งนี้ใช้ได้เฉพาะในเกมเท่านั้น"
  no-permission: "&cคุณไม่มีสิทธิ์ใช้งานคำสั่งนี้!"
  not-enough-shards: "&cคุณมี Shards ไม่เพียงพอ!"
  buy-success: "&aซื้อ %item% สำเร็จ!"
  buy-cancelled: "&cยกเลิกการซื้อแล้ว"
  reload-success: "&aรีโหลดการตั้งค่าสำเร็จ!"
  item-added: "&aเพิ่มไอเทมลงร้านค้าสำเร็จ!"

  # %shards% จะถูกแทนที่ด้วยจำนวน Shards ของผู้เล่น (เช่น 1,000)
  you-have-shards: "&eคุณมี: &f%shards% Shards"

  # ชื่อของหน้าต่างร้านค้าหลัก
  shop-title: "&5ร้านค้า Shard"

  # ชื่อของหน้าต่างยืนยันการซื้อ
  confirm-title: "&6ยืนยันการซื้อ"

  # ข้อความในแชทเมื่อได้รับ Shards. %amount% คือจำนวนที่ได้รับ
  shards-receive: "&aคุณได้รับ &e+%amount% &aShards!"

  # ข้อความบน Action bar เมื่อได้รับ Shards
  shards-receive-bar: "&a+%amount% Shards!"

# การตั้งค่าสำหรับหน้าต่างกราฟิก (GUI)
shop-ui:
  # บรรทัดคำอธิบาย (lore) ที่จะถูกเพิ่มเข้าไปในไอเทมร้านค้าเพื่อแสดงราคา
  # %cost% จะถูกแทนที่ด้วยราคาของไอเทม
  price-lore: "&eราคา: &f%cost% Shards"

  # ไอเทมที่ใช้เป็นช่องว่างสำหรับตกแต่งพื้นหลัง GUI
  blank:
    type: GRAY_STAINED_GLASS_PANE
    # ช่องที่จะเติมด้วยไอเทมนี้
    slots: [0,1,2,3,4,5,6,7,8,9,10,12,14,16,17,18,19,20,21,22,23,24,25,26]
    display: " "

  # ไอเทมที่ใช้สำหรับช่องที่ตกแต่งเท่านั้นและไม่สามารถซื้อได้
  cannotbuy:
    # รายชื่อช่องที่จะเติมด้วยไอเทมนี้ในร้านค้าหลัก
    slots: [0,1,2,3,4,5,6,7,8]
    type: BLACK_STAINED_GLASS_PANE
    display: "&7ไม่มีไว้สำหรับขาย"
    lore:
      - "&8ไอเทมชิ้นนี้ไม่สามารถซื้อได้"

  # ปุ่ม 'ยกเลิก' ในหน้าต่างยืนยันการซื้อ
  cancel:
    type: RED_STAINED_GLASS_PANE
    # ช่องสำหรับปุ่มยกเลิก
    slot: 11
    display: "&cยกเลิก"

  # ปุ่ม 'ยืนยัน' ในหน้าต่างยืนยันการซื้อ
  confirm:
    type: GREEN_STAINED_GLASS_PANE
    # ช่องสำหรับปุ่มยืนยัน
    slot: 15
    display: "&aยืนยัน"

  # ช่องที่ใช้แสดงไอเทมที่กำลังจะซื้อในหน้าต่างยืนยัน
  item-slot: 13